### ISSUE TITLE
Uncaught (in promise) No current world

### ISSUE THREAD

**Issue by galexrt** [JLyne/LiveAtlas#1]
We are using the dynmap's JSON file output.

![image](https://user-images.githubusercontent.com/3718398/102836512-dc7c8d80-43f9-11eb-9a18-a9a591e02cd6.png)

The json content of the `dynmap_config.js...` is loaded successful and valid JSON:
![image](https://user-images.githubusercontent.com/3718398/102836579-fddd7980-43f9-11eb-939a-4b0c56666226.png)

I have also verified that the json contains the `defaultworld` value (`world`). The server has only one world.

(I tested with the current v0.4 and `master` branch (47ae7a760e92ca8b2dc482b305a5399683955f57).

Any idea where I'm going the wrong way in dynmap or LiveAtlas config?

**Comment by JLyne** [comment]
Hmm, could you post the contents of your dynmap_config.json? Sounds like it isn't able to find a world/map to work with which is odd.

**Comment by galexrt** [comment]
@JLyne Sure, here you go: 
[dynmap_config.json.txt](https://github.com/JLyne/LiveAtlas/files/5727239/dynmap_config.json.txt)

Thanks for the fast response!

**Comment by JLyne** [comment]
I see the problem. It appears the `defaultmap` in your config is set to `flat`, rather than `surface_se_30` (which is your only map).

When that happens, LiveMap is supposed to fall back to the first map for the world instead, but a typo has prevented this from happening.

Will get that fixed shortly, in the meantime changing `defaultmap` to `surface_se_30` in configuration.txt should solve the problem for you.

**Comment by galexrt** [comment]
Thank you very much for the quick fix of the issue!

Updating the dynmap config option and using latest `master` LiveAtlas build it works.
