### ISSUE TITLE
marker label apostrophe rendered as html code &#96;

### ISSUE THREAD

**Issue by MattHardwick34** [JLyne/LiveAtlas#172]
title says it all, marker label apostrophe rendered as html code (`&#96;`) rather than the actual `'` character.

![image](https://user-images.githubusercontent.com/36822930/135145396-4af256af-5f86-47e8-952e-c43203956904.png)

**Comment by JLyne** [comment]
This seems to be an issue with Dynmap (or a Dynmap addon) where non-HTML (`markup: false`) markers still have HTML-y things in their labels encoded, despite the frontend already treating them as plain text and therefore requiring no encoding. Until this issue is resolved in Dynmap, LiveAtlas now decodes entities in markers with `markup: false` to fix any occurrences of this it comes across.

**Comment by MattHardwick34** [comment]
yes I did check afterwards and it appeared to be happening in legacy dynamp interface too - sorry I should have checked that before logging the issue but thank you so much for the fast turn around <3
