### ISSUE TITLE
Use `@types/dynmap` for Dynmap core API

### ISSUE THREAD

**Issue by SNDST00M** [JLyne/LiveAtlas#224]
Good news: `@types/dynmap~3.1.0` is out, it could be leveraged for global objects and interfaces from Dynmap core.

**Comment by JLyne** [comment]
Having a go at making use of this now, will see how it goes

**Comment by JLyne** [comment]
Seems to work well for the most part and has allowed me to remove some of my Dynmap specific typings which is nice.
However I did run into a few issues with incorrect typings. I'm not sure where to report these so I'll document them here:

## Options
 * Missing `followmap` (`string | null` I think) and `followzoom` (`number | null` I think)

## WorldMapConfiguration
 * Missing `append_to_world` (`?string`, only exists if configured)
 * `icon` should be `string | null` instead of `L.CustomIcon | null`  (It contains an icon URL)

## WorldMapOptions
 * `append_to_world` should be `?string` instead of `?boolean` (It contains the name of the world to append to)

## Configuration
 * Missing `showlayercontrol` (`string` or `"true" | "false" | "pinned"`)

## Marker
 * `minzoom` is mispelled `mixzoom`

## MarkerCircle
 * Isn't `export`ed
 * `yr` should be `zr`

## MarkerLine
`x`, `y` and `z` should be `number[]` (They are all arrays of coordinates)

**Comment by SNDST00M** [comment]
Best to commit those to https://github.com/DefinitelyTyped/DefinitelyTyped, I can do so if you'd prefer not to.

**Comment by SNDST00M** [comment]
> icon should be string | null instead of L.CustomIcon | null (It contains an icon URL)

I'm working on the fixes but there is the issue of the `icon` member becoming an `L.CustomIcon` after Dynmap instantiates. So I've opted to use string | L.CustomIcon | null.

**Comment by SNDST00M** [comment]
Thanks, these are fixed now and the update will be published 10am UTC.

**Comment by JLyne** [comment]
Implemented what I can for now. Has definitely improved the response parsing side of things 👍
