### ISSUE TITLE
Trying to load unrendered tiles

### ISSUE THREAD

**Issue by Naoto-0416** [JLyne/LiveAtlas#26]
![2021-05-26 (4)](https://user-images.githubusercontent.com/66252155/119640454-97023780-be53-11eb-98b6-8293c72626cc.png)
![2021-05-26 (5)](https://user-images.githubusercontent.com/66252155/119640476-9e294580-be53-11eb-9855-34b5f2d80e53.png)

**LiveAtlas Version: 1.1.0**
**Dynmap Version: 3.1-457**
**Server Version: Paper 1.16.5**
When I move into blank on the map, HTTP 404 error appears.

**Comment by JLyne** [comment]
This is normal behaviour as LiveAtlas (and vanilla dynmap) cannot know whether tiles exist without attempting to fetch them. If you would rather not see 404s in the console and you're using an external webserver, you could perhaps configure it to return a blank image instead of a 404 if a file doesn't exist (`try_files` would allow you to do this in nginx). This is out of scope for LiveAtlas though.

**Comment by Naoto-0416** [comment]
I understood. Thank you.
I love LiveAtlas because it works well on my laptop with touchscreen. vanilla Dynmap doesn't work on it.
Thanks for making LiveAtlas.
