### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by winnipeg21** [JLyne/LiveAtlas#3]
Hey there! Love the addon to Dynmap really brings an old outdated UI to life.

Anyway, I use Dynmap along with Dynmap-Towny and use the info windows. For the info windows, I have custom styling. But it seems when you load the page for the first time the CSS isn't applied until a few seconds later. Currently it's on my test server but I will upload it so I can link it.

When I first open the map - https://s.pingu.ga/kBx8b
About 10-15 seconds later - https://s.pingu.ga/38N4u (what it should be)

**Comment by JLyne** [comment]
Interesting issue, can't think why that would be happening to be honest. Do you have a link available for this?

**Comment by winnipeg21** [comment]
Sorry for the late reply. I managed to upload it to my public test server

URL - http://ds1.dlc.gg:7513/

**Comment by JLyne** [comment]
From what I can see it appears to be an issue with the info window HTML rather than any CSS.
The initial HTML the info windows have on load is different to the HTML returned in subsequent updates from dynmap.

HTML on load:
![msedge_kfzX8OCDZv](https://user-images.githubusercontent.com/4615316/103059495-349fc500-459d-11eb-9604-7a82eb9cae19.png)

HTML after an update:
![AOqtJqQm6k](https://user-images.githubusercontent.com/4615316/103059498-36698880-459d-11eb-9125-6d1f4d457702.png)

Note the missing <hr> tags in the initial version, which then appear after an update.

I haven't used the server side marker API that much, but my guess here would be your custom HTML is only being applied to area updates sent by the towny plugin, and the actual areas aren't being saved with that HTML in them. That would result in the behaviour seen here, where the default HTML is briefly visible before an update replaces it.

**Comment by winnipeg21** [comment]
Ah so the custom HTML isn't applied until a towny updates happens (which is about 10secs) so that's causing the issue. So anyway to fixed this or would it be more towny's thing?

**Comment by winnipeg21** [comment]
Wait, so could I fix this by using <style> in the info window so the css applies at the same time?
