### ISSUE TITLE
Refreshing/Direct URL gives 404? 

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#33]
Very strange one here, maybe it's the method I'm testing the Atlas map UI. I've got it standalone and pointing to the public configs of my Dynmap.

Issue:
When you use a Direct link, it'll 404.
https://api.piratemc.com/atlas/survival#PirateCraft_1;surface;-1768,64,438;2

When you zoom in and refresh the page it will 404.

But when you use the Atlas from https://api.piratemc.com/atlas/ and zoom in the URL will change and it will load fine.

What is causing this?

**Comment by JLyne** [comment]
The most likely reason for this is the webserver is not configured correctly. In your case, for multiple server support to work, the webserver needs to be configured to return LiveAtlas' index.html for URLs beginning with `/atlas/` that would otherwise 404. See the [wiki page for multiple servers](https://github.com/JLyne/LiveAtlas/wiki/Configuring-Multiple-Servers#setup) for an nginx example.  Replacing `/map/` with `/atlas/` should be enough to get it working for you.

**Comment by TomLewis** [comment]
Brilliant! Thank you!
