### ISSUE TITLE
cannot see players

### ISSUE THREAD

**Issue by paj1s** [JLyne/LiveAtlas#395]
After the exhausting setup (it was my fault, typo in the config) the map is finally showing up but without players, i don't know what can be cause of this. The dynmap internal server was working just fine last time i tried it before switching to liveatlas.

**Comment by JLyne** [comment]
My first guess would be the update request is failing. Try visiting the `update` URL you configured directly to see what it is returning.

Alternatively feel free to provide a link to your map here so I can look.

**Comment by paj1s** [comment]
thank you for support, here is link to live atlas
https://www.coolcraft.cz/dynmap/index.html
and here is a link to dynmap
https://www.coolcraft.cz/dynmap/survival/index.html

**Comment by JLyne** [comment]
Looks like https://www.coolcraft.cz/dynmap/survival/standalone/update.php is returning a 404.

The file does exist, so the most likely cause here is [this check](https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/resources/extracted/web/standalone/update.php#L35) failing, meaning the script cannot access the json file dynmap stores the latest map state in.

The most likely reason for this is that you haven't configured `webpath` correctly in dynamp's configuration.txt. For this configuration it should be set to the [full absolute path](https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics#step-3-copying-files-to-your-webserver-and-change-paths) of your `web` folder. This isn't a configuration I've worked with before, so you may need to ask for help in the dynmap discord if you can't get this to work.

Alternatively, you can ignore the above and set your `update` URL to `https://www.coolcraft.cz/dynmap/survival/standalone/dynmap_{world}.json?_={timestamp}`, which will fetch the json file directly. The file is there so that should work fine.

**Comment by paj1s** [comment]
Its weird, i have set the correct absolute path and im sure it is correct because it generated the files there and it is using them + i checked the path now. I tried to set the update url to the json file and it still doesnt work although the file is reachable.
