### ISSUE TITLE
Return 304 for request with current header

### ISSUE THREAD

**Issue by RuofengX** [JLyne/LiveAtlas#43]
**Feature Description:** *Dynmap could return 304 code to those request with correct 'If-Modified-Since' header, which could boost much performance.*

* **Additional context:** *This feature comes from the client-side cache and CDN.  CDN has a feature that it could refresh all the modified resources, such as tiles with players building, but not touch those tiles in the wild. This feature is so awesome that it could make the map loading faster meanwhile keep the necessary tiles fresh. CDN also need server-side to response a 304 when using 'If-Modified-Since' header.*

**Comment by JLyne** [comment]
From my understand this is an issue that needs to be resolved on Dynmap's side rather than LiveAtlas.

LiveAtlas is currently loading tiles via `<img>` tags, which means the browser is in control of the request and LiveAtlas cannot add additional headers. The browser will choose to add `If-Modified-Since` headers to these requests if it has previously received headers that indicate it should, such as `Last-Modified`  and appropriate `Cache-Control` headers. It is up to dynmap to send these headers.

Looking at Dynmap's PHP files for tile requests, it does set a `Last-Modified` header, but does not explicitly set a `Cache-Control` header. This causes the default PHP setting for this header to be used instead, which is typically to not allow caching at all (`no-cache, no-store, must-revalidate`). Adding a more appropriate cache control header into the script itself, such as `public`, resolves this problem and allows the browser to cache the tiles and send `If-Modified-Since` headers. I have not checked how the internal server handles this but I imagine it is similar.

Even if the headers are all correct however, it is still up to dynmap to respond to them appropriately. In the php files there is currently no logic to check for any `If-Modified-Since` header, or to return a 304 if the tile hasn't changed. This could theoretically be added, but falls outside of the scope of LiveAtlas at this time.

If LiveAtlas ever provides its own version of Dynmap's PHP files in the future then this could be an improvement to consider.

**Comment by RuofengX** [comment]
Could you solve this problem(maybe a pr in dynmap repository)? I am trying to write a serverless function to refresh those tiles which has been changed on cdn, so it cloud both boost hit chance and bandwidth efficiency🙄.
