### ISSUE TITLE
Map keeps loading the chunks over and over again from the server

### ISSUE THREAD

**Issue by ChristopherHaws** [JLyne/LiveAtlas#483]
Hello,

I think there is a bug that is causing the browser to keep requesting the chunks/regions from the server in an infinite loop. Here is my network tab of me loading the map and letting it sit there without touching it at all. You can see that there are thousands of web requests and over a GB of data transferred.

![image](https://user-images.githubusercontent.com/5934505/187043603-be72cd95-f1ab-4913-a88a-58ed0be4052c.png)

**Comment by JLyne** [comment]
Sorry for the extremely delayed reply. This is expected behaviour for Pl3xmap/Squaremap maps (which this map appears to be).

LiveAtlas mirrors Squaremap's mechanism for tile updates, which is to just request all the visible tiles again periodically. This is inherently less efficient then dynmap's approach of flagging individual tiles as needing updates, but Squaremap respects cache headers and will return 304s for unchanged tiles to reduce unneeded bandwidth use. They will still add up significantly over time if players are actively building though, due to the large area each tile covers.

Unfortunately the refresh interval is controlled by `map.background-render.interval-seconds` in Squaremap's config, and is thus tied to server-side rendering speed. It may be worth asking them to decouple those settings if it is a problem.
